package business

import (
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

// InitGeneratedBusinessModules is auto-generated by the low-code generator.
// In production, this function is populated with generated business module
// initialization calls. It is intentionally empty when no generated modules exist.
func InitGeneratedBusinessModules(r *gin.RouterGroup, db *gorm.DB) {
}
