import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

// The generated-artifact marker is written by the generator, asserted by the
// check:generated gate and matched by the reset tooling. It is declared in three
// places on purpose (they run in different toolchains), so a silent edit on one
// side is the failure mode worth guarding: the gate would then fail every
// artifact, or worse, stop recognizing hand-edited generated files.
const markerSources = [
  'scripts/harness/check-generated.mjs',
  'frontend/scripts/cleanup-generated-modules.mjs',
  'frontend/src/modules/lowcode/generator/exporter.ts',
];

const markerPattern = /GENERATED_MARKER\s*=\s*'([^']+)'/;

test('every tool that declares the generated marker declares the same sentence', () => {
  const declared = new Map();

  for (const relativePath of markerSources) {
    const content = fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
    const match = markerPattern.exec(content);
    assert.ok(match, `${relativePath} must declare GENERATED_MARKER`);
    declared.set(relativePath, match[1]);
  }

  const values = new Set(declared.values());
  assert.equal(
    values.size,
    1,
    `GENERATED_MARKER diverged across tools: ${JSON.stringify([...declared], null, 2)}`,
  );

  assert.equal(
    [...values][0],
    'Code generated by pantheon low-code generator. DO NOT EDIT.',
    'the marker sentence is the contract other repos and the Go generated-code convention match on',
  );
});

test('the generator marks every file it exports', () => {
  const exporterSource = fs.readFileSync(
    path.join(repoRoot, 'frontend/src/modules/lowcode/generator/exporter.ts'),
    'utf8',
  );

  // generateAll() is the single choke point; if a new template stops routing
  // through the marker helper, exported files silently lose their marker.
  assert.match(exporterSource, /content:\s*withGeneratedMarker\(/);
});
