import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const TEST_DIR = path.dirname(fileURLToPath(import.meta.url));
const SCRIPT = path.resolve(TEST_DIR, '..', '..', 'scripts', 'harness', 'check-generated.mjs');

const MARKER = 'Code generated by pantheon low-code generator. DO NOT EDIT.';
const MARKED = [
  'backend/modules/business/generated_registry.go',
  'backend/modules/system/iam/menu/generated_component_registry.go',
  'frontend/src/modules/generated/business.ts',
  'frontend/src/modules/generated/system.ts',
  'frontend/src/core/router/generatedComponentRegistry.ts',
  'frontend/src/i18n/resources/generated/zh-CN.ts',
  'frontend/src/i18n/resources/generated/en-US.ts',
  'frontend/src/i18n/resources/generated/ko-KR.ts',
  'frontend/src/i18n/resources/generated/ja-JP.ts',
  'frontend/src/i18n/resources/generated/fr-FR.ts',
];

function createRoot() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'generated-check-'));
  const write = (relative, content) => {
    const full = path.join(root, relative);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  };
  for (const relative of MARKED) {
    write(relative, `// ${MARKER}\n\nexport const x = {};\n`);
  }
  write('schema/generated/feature-ledger.json', JSON.stringify({ version: 1, entries: [] }));
  return { root, write };
}

function run(root, extra = []) {
  return spawnSync(process.execPath, [SCRIPT, '--json', '--strict', '--root', root, ...extra], { encoding: 'utf8' });
}

test('passes when every artifact carries the first-line marker', () => {
  const { root } = createRoot();
  const result = run(root);
  assert.equal(result.status, 0, result.stdout);
  assert.equal(JSON.parse(result.stdout).findingCount, 0);
});

test('flags a generated artifact missing its marker', () => {
  const { root, write } = createRoot();
  write('frontend/src/modules/generated/business.ts', "import type { ModuleConfig } from '../../core/router/types';\n");
  const result = run(root);
  assert.equal(result.status, 1);
  const body = JSON.parse(result.stdout);
  assert.equal(body.findings[0].rule, 'generated-marker-missing');
});

test('flags a marker that is not the first line', () => {
  const { root, write } = createRoot();
  write('frontend/src/core/router/generatedComponentRegistry.ts', `\n// ${MARKER}\nexport const x = {};\n`);
  const result = run(root);
  assert.equal(result.status, 1);
  assert.equal(JSON.parse(result.stdout).findings[0].rule, 'generated-marker-not-first-line');
});

test('flags a missing generated artifact', () => {
  const { root } = createRoot();
  fs.rmSync(path.join(root, 'backend/modules/business/generated_registry.go'));
  const result = run(root);
  assert.equal(result.status, 1);
  assert.equal(JSON.parse(result.stdout).findings[0].rule, 'generated-artifact-missing');
});

test('flags an unparseable generated JSON artifact', () => {
  const { root, write } = createRoot();
  write('schema/generated/feature-ledger.json', '{ not json');
  const result = run(root);
  assert.equal(result.status, 1);
  assert.equal(JSON.parse(result.stdout).findings[0].rule, 'generated-artifact-invalid');
});

test('report-only mode exits 0 even with findings', () => {
  const { root, write } = createRoot();
  write('frontend/src/modules/generated/business.ts', 'no marker\n');
  const result = spawnSync(process.execPath, [SCRIPT, '--root', root], { encoding: 'utf8' });
  assert.equal(result.status, 0);
  assert.match(result.stdout, /finding\(s\)/);
});

test('flags a dynamically discovered generated module file missing the marker', () => {
  const { root, write } = createRoot();
  write('backend/modules/business/order/order_model.go', 'package order\n');
  const result = run(root);
  assert.equal(result.status, 1);
  const body = JSON.parse(result.stdout);
  assert.equal(body.findings[0].rule, 'generated-marker-missing');
  assert.equal(body.findings[0].file, 'backend/modules/business/order/order_model.go');
});

test('flags a generated frontend module file missing the marker', () => {
  const { root, write } = createRoot();
  write('frontend/src/modules/business/order/api.ts', "export const endpoint = '/business/order';\n");
  const result = run(root);
  assert.equal(result.status, 1);
  const body = JSON.parse(result.stdout);
  assert.equal(body.findings[0].rule, 'generated-marker-missing');
  assert.equal(body.findings[0].file, 'frontend/src/modules/business/order/api.ts');
});

test('flags an unparseable generated module schema JSON', () => {
  const { root, write } = createRoot();
  write('schema/generated/business/order.json', '{ not json');
  const result = run(root);
  assert.equal(result.status, 1);
  const body = JSON.parse(result.stdout);
  assert.equal(body.findings[0].rule, 'generated-artifact-invalid');
  assert.equal(body.findings[0].file, 'schema/generated/business/order.json');
});

test('accepts marked generated module files and parseable schema JSON', () => {
  const { root, write } = createRoot();
  write('backend/modules/business/order/order_model.go', `// ${MARKER}\n\npackage order\n`);
  write('frontend/src/modules/business/order/api.ts', `// ${MARKER}\n\nexport const x = {};\n`);
  write('schema/generated/business/order.json', JSON.stringify({ name: 'order', scope: 'business' }));
  const result = run(root);
  assert.equal(result.status, 0, result.stdout);
  const body = JSON.parse(result.stdout);
  assert.equal(body.findingCount, 0);
  // 10 stable marked + 1 registry (MARKED) + feature-ledger + 3 discovered.
  assert.equal(body.checkedCount, MARKED.length + 1 + 3);
});

test('ignores hand-written files outside the generator-owned business scope', () => {
  const { root, write } = createRoot();
  write('backend/modules/system/i18n/i18n_model.go', 'package system\n');
  write('frontend/src/modules/system/i18n/api.ts', "export const endpoint = '/system/i18n';\n");
  write('schema/generated/feature-ledger-extra.json', '{"unexpected": true}');
  const result = run(root);
  // system-scope sources are hand-written (no marker expected); the stray JSON
  // sits directly in schema/generated/ (not a scope dir), so only the stable
  // artifacts are checked and everything passes.
  assert.equal(result.status, 0, result.stdout);
  assert.equal(JSON.parse(result.stdout).findingCount, 0);
});
